databaseChangeLog:
-  changeSet:  
     id:  alterTable-Application  
     author:  Ananda  
     changes:  
     -  addColumn:  
          tableName:   Application  
          columns:  
            -  column:  
                 name:  Expiration  
                 type:  datetime getdate()
                 constraints:
                   nullable: false