INSERT INTO [dbo].[WhiteHouseVisitorLog]
           ([VisitorId]
           ,[UIN]
           ,[BDGNBR]
           ,[ACCESS_TYPE]
           ,[TOA]
           ,[POA]
           ,[TOD]
           ,[POD]
           ,[APPT_MADE_DATE]
           ,[APPT_START_DATE]
           ,[APPT_END_DATE]
           ,[APPT_CANCEL_DATE]
           ,[Total_People]
           ,[LAST_UPDATEDBY]
           ,[POST]
           ,[LastEntryDate]
           ,[TERMINAL_SUFFIX]
           ,[visitee_namelast]
           ,[visitee_namefirst]
           ,[MEETING_LOC]
           ,[MEETING_ROOM]
           ,[CALLER_NAME_LAST]
           ,[CALLER_NAME_FIRST]
           ,[CALLER_ROOM]
           ,[Description]
           ,[Release_Date])

SELECT B.VisitorId
	  ,[UIN]
      ,[BDGNBR]
      ,[ACCESS_TYPE]
      ,[TOA]
      ,[POA]
      ,[TOD]
      ,[POD]
      ,[APPT_MADE_DATE]
      ,[APPT_START_DATE]
      ,[APPT_END_DATE]
      ,[APPT_CANCEL_DATE]
      ,[Total_People]
      ,[LAST_UPDATEDBY]
      ,[POST]
      ,[LastEntryDate]
      ,[TERMINAL_SUFFIX]
      ,[visitee_namelast]
      ,[visitee_namefirst]
      ,[MEETING_LOC]
      ,[MEETING_ROOM]
      ,[CALLER_NAME_LAST]
      ,[CALLER_NAME_FIRST]
      ,[CALLER_ROOM]
      ,[Description]
      ,[Release_Date]
  FROM [dbo].[WhiteHouseLog] A
  INNER JOIN Visitor B
  ON A.NAMEFIRST= B.FirstName 
  AND A.NAMELAST = B.LastName
  AND A.NAMEMID = B.MiddleName;